# permissions for end users to view mykubeapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mykybeapps-viewer-role
rules:
- apiGroups:
  - yogeshsurapaneni.com
  resources:
  - mykubeapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yogeshsurapaneni.com
  resources:
  - mykubeapps/status
  verbs:
  - get
