# permissions for end users to edit mykubeapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mykubeapps-editor-role
rules:
- apiGroups:
  - yogeshsurapaneni.com
  resources:
  - mykubeapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yogeshsurapaneni.com
  resources:
  - mykubeapps/status
  verbs:
  - get
